stages:
    - test

variables:
    GO111MODULE: "on"

.test: &test_template
    stage: test
    services:
        - name: apache/couchdb:2.3.1
          alias: couch23
    variables:
        COUCHDB_USER: admin
        COUCHDB_PASSWORD: abc123
        KIVIK_TEST_DSN_COUCH23: http://admin:abc123@couch23:5984/
    before_script:
        - ./script/complete_couch2.sh ${KIVIK_TEST_DSN_COUCH23}
    script:
        - go mod download
        - go test -race ./...

lint:
    stage: test
    image: golangci/golangci-lint:v1.24
    script:
        - go mod download
        - golangci-lint run ./...

coverage:
    stage: test
    image: golang:1.14
    script:
        - go mod download
        - ./script/coverage.sh

go-1.13:
    <<: *test_template
    image: golang:1.13

go-1.14:
    <<: *test_template
    image: golang:1.14

go-rc:
    <<: *test_template
    image: golang:rc
    allow_failure: true
